version: '3.9'

services:
  proj:
    image: michallefler/proj:v1
    container_name: proj
    build:
      context: .
      dockerfile: Dockerfile
      args:
        platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  proj-dev:
    image: michallefler/proj-dev:latest
    container_name: proj-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
